# Generated by Django 3.2.9 on 2022-01-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, help_text='pesian name if exist', max_length=100, null=True)),
                ('ename', models.CharField(blank=True, help_text='pesian name if exist', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='this the uniquer extracing from url for each movie', max_length=50, null=True)),
                ('fname', models.CharField(blank=True, help_text='pesian name if exist', max_length=500, null=True)),
                ('ename', models.CharField(blank=True, help_text='english name if exist', max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, help_text='tvshow or movie', max_length=100, null=True)),
                ('original_url', models.CharField(blank=True, help_text='refer to filimo page', max_length=1000, null=True, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, help_text='url extract from filimo', max_length=1000, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('filimo_rating', models.FloatField(blank=True, null=True)),
                ('filimo_total_votes', models.BigIntegerField(blank=True, null=True)),
                ('genres', models.ManyToManyField(blank=True, to='movie.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('vote_up', models.IntegerField(blank=True, null=True)),
                ('vote_down', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_movie', to='movie.movie')),
            ],
        ),
    ]
