# Generated by Django 3.2.9 on 2022-01-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_comment_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='ename',
            field=models.CharField(blank=True, help_text='english name if exist', max_length=100, null=True),
        ),
    ]
