# Generated by Django 3.2.9 on 2022-02-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_genre_ename'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='polarity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
