# Generated by Django 3.2.9 on 2022-02-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_comment_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='polarity',
            field=models.FloatField(blank=True, help_text='this represent the sentiment analysis of this commnent -1 to 1 ', null=True),
        ),
    ]
