# Generated by Django 3.2.9 on 2022-02-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_comment_polarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='e_text',
            field=models.TextField(blank=True, help_text='english translated version', max_length=1000, null=True),
        ),
    ]
