# Generated by Django 3.2.9 on 2022-02-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_comment_e_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='final number of sentiment analysis based on the comments', null=True),
        ),
    ]
