# Generated by Django 3.2.9 on 2022-02-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sentiment_detail',
            field=models.JSONField(blank=True, help_text='this is for the number of each point [-1, 0.5, 0. 0.5 , 1] based on the number of comments', null=True),
        ),
    ]
