# Generated by Django 3.2.9 on 2022-02-13 21:16

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_sentiment_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sentiment_detail',
            field=models.JSONField(blank=True, default=movie.models.call_default_sentiment, help_text='this is for the number of each point [-1, 0.5, 0. 0.5 , 1] based on the number of comments', null=True),
        ),
    ]
